# Site settings
#
baseurl: "/"
exclude: ['README.md']
# kramdown y rouge are now the default setting for markdown and highlighter respectively in Jekyll 3.0 and above
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    syntax_highlighter: "rouge"
timezone: "America/Phoenix"
# gems: octopress-date-format
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Robert Weber, Director"
