# Site settings
#
# Date of this Update to Config-template file ver 08-13-2017 PM
#
# github: [metadata]
# theme: "jekyll-theme-cayman"
# repository: MMINAIL/mminail.github.io
title: "Concept Library"
tagline: "A GitHub repo of Lessons and Articles that emphasize both the GFM and Kramdown engines"
description: "A GitHub repo of Lessons and Articles that emphasize both the GFM and Kramdown engines"
twitter:
    username: "mminail"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "rwebaz"
    twitter_username: "rwebaz"
# The 'baseurl' is the subpath of your designated project, e.g. /Liquid-Lessons-Project
baseurl: "/"
# The 'url' is the parental web address of your designated project, e.g. /https://rwebaz.github.io
url: "https://mminail.github.io"
exclude: ['README.md']
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
    math_engine: "mathjax"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-7]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/MMI-Medmj-Org-Got-Tree-Flammarion-Person-Through-Celestial-Sphere-circle-100-x-100.png
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"
      author: "Robert Weber, Director"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default" 
      author: "Robert Weber, Director"
collections:
  collection_CFFP:
    output: "true"
defaults:
  - scope:
      path: ""
      type: "collection_LLP"
    values:
      layout: "page"
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
