# Site settings
# 
# Date of this Update to Config-template file ver 02-06-2018 pm
# 
# Uncomment theme for docs folder
# theme: "jekyll-theme-cayman"
# 
# There is one main repository as of 12-31-17
# repository: https://www.github.com/MMINAIL/mminail.github.io
#
# There are approx sixty auxillary repositories as of 12-31-17
# repository: https://www.github.com/rwebaz/Blank-Lessons-Project
# 
title: "Concepts Library | MMINAIL"
lang: "en-US"
tagline: "A GitHub repo of Lessons and Articles that emphasize both the GFM and Kramdown development engines"
description: "The Concept Library of the MMINAIL is a GitHub repo of Lessons and Articles emphasizing both the GFM and Kramdown development engines."
twitter:
    username: "mminail"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "rwebaz"
    twitter_username: "rwebaz"
# The 'baseurl' is the subpath of your designated project, e.g. /Blank-Lessons-Project or /blog or simply "/"
baseurl: "/"
# The 'url' is the parental web address of your designated project, e.g. /https://rwebaz.github.io
url: "https://mminail.github.io"
exclude: ['README.md']
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
    math_engine: "mathjax"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-7]
# Settings For Default Keys: Use a scope/values pair
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/png"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/svg"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      category: "mminail"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      category: "mminail" 
excerpt_separator: <!-- this is a literal excerpt separator -->
collections:
  gists:
    output: "true"
defaults:
  - scope:
      path: "_gists"
      type: "pages"
    values:
      category: "mminail"
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.old
