baseurl: /
exclude: ['README.md']
#kramdown y rouge are now the default setting for markdown and highlighter respectively in Jekyll 3.0 and above
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
defaults:
  -
    scope:
      path: "" # By placing an empty string here ALL of the files in the project will be served with the layout "default"
      type: "pages" # The type attribute limits the files served with the layout "default" to "pages" only
    values:
      layout: "default"
timezone: America/Phoenix
#gems: octopress-date-format
