# Site settings
# 
# underscore Config dot yaml (_config.yml) template ver 09-04-21
# 
# Un-comment the theme for the `docs` folder [only] in satellite repos
# Note. This is a `main repo`.
#
# theme: "jekyll-theme-cayman"
# 
# There is one main repository as of 11-11-19
# repository: https://www.github.com/mminail/mminail.github.io
#
# There are approx Sixty satellite repositories as of 11-11-19
# repository: https://www.github.com/rwebaz/rwebaz.github.io
#
# There is also one new repository as of 11-11-19
# repository: https://www.github.com/exvivospace/exvivospace.github.io
#
# And, another main repository ...
# repository: https://www.github.com/Medcoin-Crypto-Currency/medcoin.github.io
# 
name: ""
lang: "en-US"
encoding: UTF-8
title: "Concepts Library | MMINAIL"
tagline: "A GitHub repo of Lessons and Articles that emphasize both the GFM and Kramdown development engines"
description: "The Concept Library of the MMINAIL is a GitHub repo of Lessons and Articles emphasizing both the GFM and Kramdown development engines."
twitter:
    username: "mminail"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "rwebaz"
    twitter_username: "mminail"
#
# Set the North American default time zone for the repo
timezone: "America/Phoenix"
# 
# The 'baseurl' is the subpath of your designated project
# 
# C=> /Blank-Lessons-Project or /blog or simply "/" for `main repos`
#
baseurl: "/"
#
# The `url` is the parental web address of your designated project
#
# C=> "https://www.github.com/mminail/mminail.github.io"
#
# C=> "https://www.github.com/rwebaz/rwebaz.github.io"
#
# C=> "https://www.github.com/exvivospace/exvivospace.github.io"
#
# C=> "https://www.github.com/Medcoin-Crypto-Currency/medcoin.github.io"
#
# Returns;
#
# C=> "https://medcoin-crypto-currency.github.io/medcoin.github.io/"
#
url: "https://mminail.github.io"
#
# The `source` tells the Jekyll engine where to locate the opening `index` file.
# In this case, the `source` of the `index.htm` is the `root` folder of the repo.
# Because this GitHub pages website is being served remotely from the `root`
# of the repo, the location of the `index` file is the `root`.
# 
# source: "mminail.github.io"
# source: [your repo's top level directory]
#
# GitHub Pages Mandatory Defaults
# 
# GitHub pages default (A)
# Do NOT produce an index for related posts
# suggested. lsi: "false" or Boolean "0";
# Produces an index for related posts when enabled "true" or Boolean "1";
# Requires the `classifier-reborn` plugin
# Note. When uncommenting a Yaml statement, remove the enveloping quotations
lsi: false
#
# GitHub pages default (B)
# Disable all custom plugins
# suggested. safe: "true"; disables all custom plugins
# Note. When uncommenting a Yaml statement, remove the enveloping quotations
safe: true
#
# GitHub pages default (C)
# Set the properties for `Gist`
# suggested. noscript: "false"; unknown
# Note. When uncommenting a Yaml statement, remove the enveloping quotations
# Warming. Property `gist` is not allowed
gist:
  noscript: "false"
#
# GitHub pages default (C)
# Disable the `Experimental Incremental Build Feature` or `EIBF` suggested, as follows:
# incremental: "false"; disables the `EIBF`
# Why? [may break site generation in some cases]
# Note. When uncommenting a Yaml statement, remove the enveloping quotations
# Warning. Author not disabling this feature nor enabling this feature
# incremental: false
# 
# GitHub pages default (D)
# Set the default `highlighter` mechanism to `Rouge`
# highlighter: rouge (with or without quotes)
highlighter: "rouge"
# 
# GitHub pages default (E)
# Set the properties for `Kramdown`
# Set the default `markdown` engine to `Kramdown`
markdown: "kramdown"
#
# Note. If you want to use another highlighter ie.) highlight.js ...
# You must then disable Jekyll's syntax highlighting by updating
# your project's _config.yml file as follows:
# kramdown:
#   syntax_highlighter_opts:
#     disable : false
#
kramdown:
    input: "GFM"
    syntax_highlighter: rouge
    math_engine: "mathjax"
#
hard_wrap: "false"
#
# Set the code for `Goodle Analytics`
# Warning. Property `google_analytics` is not allowed
google_analytics:
  [UA-44765001-7]
#
# Settings For Default Keys: Use a scope/values pair
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/png"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/svg"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"
      author: "Robert Weber, Director"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      ayout: "default" 
      author: "Robert Weber, Director"
defaults:
  - scope:
      path: "_gists"
      type: "pages"
    values:
      category: "mminail"
#
excerpt_separator: <!-- this is a literal excerpt separator -->
#
collections:
  gists:
    output: "true"
#
plugins_dir:
  jekyll-feed
  jekyll-seo-tag
  jekyll-sitemap
#
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.old
#
# Exclude the default `README.md` file when rendering Jekyll, as follows:
exclude:
  ['README.md']
#
# No newline at end of file
